#!/bin/bash

set -e

readonly X11VNC_EXEC_FILE="/usr/bin/x11vnc"

readonly X11VNC_RC_FILE_NAME="systemd-x11vnc.x11vncrc"
readonly X11VNC_SYSTEM_RC_FILE="/etc/systemd-x11vnc/${X11VNC_RC_FILE_NAME}"
readonly X11VNC_USER_RC_FILE="${HOME}/.config/systemd-x11vnc/${X11VNC_RC_FILE_NAME}"

declare -ir BASE_RFB_PORT=5900

[[ ( -n "${HOME:-}" ) && ( -d "${HOME:-}" ) ]] || { printf "--" 'Invalid HOME environment variable value: %s\n' "${HOME:-}" 1>&2 && exit 1; }

[[ ( -n "${DISPLAY:-}" ) && ( "${DISPLAY:-}" =~ ^:(0|[1-9][[:digit:]]*)$ ) ]] || \
    { printf "--" 'Invalid DISPLAY environment variable value: %s\n' "${DISPLAY:-}" 1>&2 && exit 1; }

declare -i rfbPort=$((${BASE_RFB_PORT} + ${BASH_REMATCH[1]}))

[[ ( -n "${XAUTHORITY:-}" ) && ( -f "${XAUTHORITY:-}" ) ]] || \
    { printf "--" 'Invalid XAUTHORITY environment variable value: %s\n' "${XAUTHORITY:-}" 1>&2 && exit 1; }

exec "${X11VNC_EXEC_FILE}" \
    -auth "${XAUTHORITY}" \
    -display "${DISPLAY}" \
    -env HOME="${HOME}" \
    -forever \
    -inetd \
    -prog "${X11VNC_EXEC_FILE}" \
    -rfbport ${rfbPort} \
    -rfbportv6 ${rfbPort} \
    -rc <(
        cat "${X11VNC_SYSTEM_RC_FILE}"
        
        ! [[ -f "${X11VNC_USER_RC_FILE}" ]] || { printf "--" '\n'; cat "${X11VNC_USER_RC_FILE}"; }
    )
